### ISSUE TITLE
Running the application does not display weather

### ISSUE THREAD

**Issue by amadib** [chrispconnolly/weatherapp#1]
Out of the box this is what I see .. is this the expected behavior?

![image](https://user-images.githubusercontent.com/326888/56867742-f8c2ef80-69b6-11e9-809d-60b63eea77c7.png)

**Comment by chrispconnolly** [comment]
@amadib You may need to insert your API key in the connection URL string within the WeatherViewModel.kt.

I just pushed new code for the first interface.  Let me know if you're able to get a build and feel free to ping me if there are issues.  Thanks for the feedback!
-Chris

**Comment by amadib** [comment]
This is what I'm receiving now from a clean clone
```
FAILURE: Build failed with an exception.

* What went wrong:
New Gradle Sync is not supported due to containing Kotlin modules using an unsupported plugin version

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

**Comment by chrispconnolly** [comment]
Are you still having this issue?  I did have a warning in my top-level build.gradle config which I fixed.  I never had this build issue but I'm going to push this change today anyways to bump the kotlin version:
buildscript {
    ext.kotlin_version = '1.3.31'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
